/* Customers */
INSERT INTO `drinkstogo_db`.`customers` (`cust_name`, `cust_email`) VALUES ('Guest', 'guest@drinkstogo.com');
INSERT INTO `drinkstogo_db`.`customers` (`cust_name`, `cust_email`) VALUES ('Store', 'store@drinkstogo.com');
INSERT INTO `drinkstogo_db`.`customers` (`cust_name`, `cust_email`) VALUES ('Sonal', 'sonalp13@gmail.com');
INSERT INTO `drinkstogo_db`.`customers` (`cust_name`, `cust_email`) VALUES ('Hebah', 'hebah.memon@gmail.com');
INSERT INTO `drinkstogo_db`.`customers` (`cust_name`, `cust_email`) VALUES ('Nida', 'nidasmemon@gmail.com');
INSERT INTO `drinkstogo_db`.`customers` (`cust_name`, `cust_email`) VALUES ('Jyochsna', 'jyochsnagongal@gmail.com');
INSERT INTO `drinkstogo_db`.`customers` (`cust_name`, `cust_email`) VALUES ('Pam', 'esq.kelly@gmail.com');

/* Products */
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Iced Coffee', 'Coffee', 'Cold','Small','2.65');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Iced Coffee', 'Coffee', 'Cold','Large','2.95');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Iced Coffee with Milk', 'Coffee', 'Cold','Small','2.65');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Iced Coffee with Milk', 'Coffee', 'Cold','Large','2.95');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Iced Espresso Classics - Vanilla Latte', 'Coffee', 'Cold','Small','2.65');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Iced Espresso Classics - Vanilla Latte', 'Coffee', 'Cold','Large','2.95');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Iced Espresso Classics - Caffe Mocha', 'Coffee', 'Cold','Small','3.05');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Iced Espresso Classics - Caffe Mocha', 'Coffee', 'Cold','Large','3.35');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Iced Espresso Classics - Caramel Macchiato', 'Coffee', 'Cold','Small','4.45');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Iced Espresso Classics - Caramel Macchiato', 'Coffee', 'Cold','Large','4.75');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Blonde Roast', 'Coffee', 'Hot','Small','2.55');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Blonde Roast', 'Coffee', 'Hot','Large','2.85');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Caffè Latte', 'Coffee', 'Hot','Small','2.95');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Caffè Latte', 'Coffee', 'Hot','Large','4.15');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Cappuccino', 'Coffee', 'Hot','Small','3.05');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Cappuccino', 'Coffee', 'Hot','Large','3.35');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Caramel Macchiato', 'Coffee', 'Hot','Small','4.45');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Caramel Macchiato', 'Coffee', 'Hot','Large','4.75');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Hot Chocolate', 'Other', 'Hot','Small','2.25');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Hot Chocolate', 'Other', 'Hot','Large','2.55');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Shaken Sweet Tea', 'Tea', 'Cold','Small','2.25');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Shaken Sweet Tea', 'Tea', 'Cold','Large','2.95');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Tazo® Bottled Organic Iced Black Tea', 'Tea', 'Cold','Small','3.00');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Tazo® Bottled Organic Iced Black Tea', 'Tea', 'Cold','Large','3.75');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Tazo® Bottled Organic Iced Green Tea', 'Tea', 'Cold','Small','3.00');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Tazo® Bottled Organic Iced Green Tea', 'Tea', 'Cold','Large','3.75');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Teavana® Shaken Iced Black Tea', 'Tea', 'Cold','Small','2.25');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Teavana® Shaken Iced Black Tea', 'Tea', 'Cold','Large','2.95');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Teavana® Shaken Iced GreenTea', 'Tea', 'Cold','Small','2.25');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Teavana® Shaken Iced GreenTea', 'Tea', 'Cold','Large','2.95');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Tazo® Bottled Tazoberry', 'Tea', 'Hot','Small','3.00');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Tazo® Bottled Tazoberry', 'Tea', 'Hot','Large','3.75');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Tazo® Bottled White Cranberry', 'Tea', 'Hot','Small','3.00');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Tazo® Bottled White Cranberry', 'Tea', 'Hot','Large','3.75');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Teavana® Mango Black Tea', 'Tea', 'Hot','Small','2.75');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Teavana® Mango Black Tea', 'Tea', 'Hot','Large','3.45');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Teavana® Passion Tango® Herbal Tea', 'Tea', 'Hot','Small','2.75');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Teavana® Passion Tango® Herbal Tea', 'Tea', 'Hot','Large','3.45');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Teavana® Peach Green Tea', 'Tea', 'Hot','Small','2.75');
INSERT INTO `drinkstogo_db`.`products` (`prod_name`, `type`, `temp`, `size`, `price`) VALUES ('Teavana® Peach Green Tea', 'Tea', 'Hot','Large','3.45');